project:
  type: website

execute:
  freeze: auto
  
website:
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
  comments: 
    utterances:
      repo: lfod/real-blog
  google-analytics: "UA-92165973-1"

format:
  html:
    include-in-header: www/banner.html
    theme: 
      - www/styles.scss



