project:
  type: website

execute:
  freeze: auto
  
website:
  site-url: "https://www.livefreeordichotomize.com"
  description: "Live Free or Dichotomize: Lucy D'Agostino McGowan & Nick Strayer's Blog"
  title: " "
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - icon: rss
        href: index.xml
  comments: 
    utterances:
      repo: lfod/lfod.github.io
  google-analytics: "UA-92165973-1"
  open-graph: true
  twitter-card:
    title: "Live Free or Dichotomize"
    creator: "@LucyStats"
    image: media/lfod-card.png
    card-style: summary_large_image

format:
  html:
    include-in-header: www/banner.html
    theme: 
      - www/styles.scss



