project:
  type: website

execute:
  freeze: auto
  
website:
  title: "livefreeordichotomize"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lfod
      - icon: twitter
        href: https://twitter.com/lucystats
  comments: 
    utterances:
      repo: lfod/real-blog
format:
  html:
    include-in-header: www/banner.html
    theme: 
      - www/styles.scss



