on:
  push:
    branches: main
  workflow_dispatch:

name: renderbook

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Setup dependencies
        run: | 
          sudo apt install libcurl4-openssl-dev
          sudo apt-get install libmagick++-dev
          sudo apt install libudunits2-dev
          sudo apt install libgdal-dev
          sudo apt-get install libharfbuzz-dev libfribidi-dev
      
      - uses: r-lib/actions/setup-r@v2
            
      - uses: r-lib/actions/setup-renv@v2

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
          
      - name: Create and populate .Renviron file
        run: |
          echo OPENCAGE_KEY="$MAPPED_OPENCAGE_KEY" >> ~/.Renviron
          echo CENSUS_API_KEY="$MAPPED_CENSUS_API_KEY " >> ~/.Renviron
        shell: bash
        env:
          MAPPED_OPENCAGE_KEY: ${{ secrets.OPENCAGE_KEY}}
          MAPPED_CENSUS_API_KEY : ${{ secrets.CENSUS_API_KEY }}
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}